spring:
  application:
    name: curth-product-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: pdata@1234
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    enabled: true
    table: schema_history

server:
  port: 8094

app:
  kafka:
    topic:
      inventory-events: product.inventory.events
      status-events: product.status.events
