/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package curthproductservice.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InventoryStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8684948534444441190L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InventoryStatus\",\"namespace\":\"curthproductservice.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"inventoryType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"productName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"productType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"createdAt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"updatedAt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InventoryStatus> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InventoryStatus> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InventoryStatus> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InventoryStatus> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InventoryStatus> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InventoryStatus to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InventoryStatus from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InventoryStatus instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InventoryStatus fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String inventoryType;
  private int quantity;
  private java.lang.String productName;
  private java.lang.String productType;
  private java.lang.String createdAt;
  private java.lang.String updatedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InventoryStatus() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param inventoryType The new value for inventoryType
   * @param quantity The new value for quantity
   * @param productName The new value for productName
   * @param productType The new value for productType
   * @param createdAt The new value for createdAt
   * @param updatedAt The new value for updatedAt
   */
  public InventoryStatus(java.lang.String id, java.lang.String inventoryType, java.lang.Integer quantity, java.lang.String productName, java.lang.String productType, java.lang.String createdAt, java.lang.String updatedAt) {
    this.id = id;
    this.inventoryType = inventoryType;
    this.quantity = quantity;
    this.productName = productName;
    this.productType = productType;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return inventoryType;
    case 2: return quantity;
    case 3: return productName;
    case 4: return productType;
    case 5: return createdAt;
    case 6: return updatedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: inventoryType = value$ != null ? value$.toString() : null; break;
    case 2: quantity = (java.lang.Integer)value$; break;
    case 3: productName = value$ != null ? value$.toString() : null; break;
    case 4: productType = value$ != null ? value$.toString() : null; break;
    case 5: createdAt = value$ != null ? value$.toString() : null; break;
    case 6: updatedAt = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'inventoryType' field.
   * @return The value of the 'inventoryType' field.
   */
  public java.lang.String getInventoryType() {
    return inventoryType;
  }


  /**
   * Sets the value of the 'inventoryType' field.
   * @param value the value to set.
   */
  public void setInventoryType(java.lang.String value) {
    this.inventoryType = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.String getProductName() {
    return productName;
  }


  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.String value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'productType' field.
   * @return The value of the 'productType' field.
   */
  public java.lang.String getProductType() {
    return productType;
  }


  /**
   * Sets the value of the 'productType' field.
   * @param value the value to set.
   */
  public void setProductType(java.lang.String value) {
    this.productType = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.lang.String getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.String value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'updatedAt' field.
   * @return The value of the 'updatedAt' field.
   */
  public java.lang.String getUpdatedAt() {
    return updatedAt;
  }


  /**
   * Sets the value of the 'updatedAt' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.lang.String value) {
    this.updatedAt = value;
  }

  /**
   * Creates a new InventoryStatus RecordBuilder.
   * @return A new InventoryStatus RecordBuilder
   */
  public static curthproductservice.avro.InventoryStatus.Builder newBuilder() {
    return new curthproductservice.avro.InventoryStatus.Builder();
  }

  /**
   * Creates a new InventoryStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InventoryStatus RecordBuilder
   */
  public static curthproductservice.avro.InventoryStatus.Builder newBuilder(curthproductservice.avro.InventoryStatus.Builder other) {
    if (other == null) {
      return new curthproductservice.avro.InventoryStatus.Builder();
    } else {
      return new curthproductservice.avro.InventoryStatus.Builder(other);
    }
  }

  /**
   * Creates a new InventoryStatus RecordBuilder by copying an existing InventoryStatus instance.
   * @param other The existing instance to copy.
   * @return A new InventoryStatus RecordBuilder
   */
  public static curthproductservice.avro.InventoryStatus.Builder newBuilder(curthproductservice.avro.InventoryStatus other) {
    if (other == null) {
      return new curthproductservice.avro.InventoryStatus.Builder();
    } else {
      return new curthproductservice.avro.InventoryStatus.Builder(other);
    }
  }

  /**
   * RecordBuilder for InventoryStatus instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InventoryStatus>
    implements org.apache.avro.data.RecordBuilder<InventoryStatus> {

    private java.lang.String id;
    private java.lang.String inventoryType;
    private int quantity;
    private java.lang.String productName;
    private java.lang.String productType;
    private java.lang.String createdAt;
    private java.lang.String updatedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(curthproductservice.avro.InventoryStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.inventoryType)) {
        this.inventoryType = data().deepCopy(fields()[1].schema(), other.inventoryType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.productName)) {
        this.productName = data().deepCopy(fields()[3].schema(), other.productName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.productType)) {
        this.productType = data().deepCopy(fields()[4].schema(), other.productType);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[6].schema(), other.updatedAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing InventoryStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(curthproductservice.avro.InventoryStatus other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.inventoryType)) {
        this.inventoryType = data().deepCopy(fields()[1].schema(), other.inventoryType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.productName)) {
        this.productName = data().deepCopy(fields()[3].schema(), other.productName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.productType)) {
        this.productType = data().deepCopy(fields()[4].schema(), other.productType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[6].schema(), other.updatedAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'inventoryType' field.
      * @return The value.
      */
    public java.lang.String getInventoryType() {
      return inventoryType;
    }


    /**
      * Sets the value of the 'inventoryType' field.
      * @param value The value of 'inventoryType'.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder setInventoryType(java.lang.String value) {
      validate(fields()[1], value);
      this.inventoryType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'inventoryType' field has been set.
      * @return True if the 'inventoryType' field has been set, false otherwise.
      */
    public boolean hasInventoryType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'inventoryType' field.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder clearInventoryType() {
      inventoryType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder setQuantity(int value) {
      validate(fields()[2], value);
      this.quantity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder clearQuantity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.String getProductName() {
      return productName;
    }


    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder setProductName(java.lang.String value) {
      validate(fields()[3], value);
      this.productName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'productType' field.
      * @return The value.
      */
    public java.lang.String getProductType() {
      return productType;
    }


    /**
      * Sets the value of the 'productType' field.
      * @param value The value of 'productType'.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder setProductType(java.lang.String value) {
      validate(fields()[4], value);
      this.productType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'productType' field has been set.
      * @return True if the 'productType' field has been set, false otherwise.
      */
    public boolean hasProductType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'productType' field.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder clearProductType() {
      productType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.lang.String getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder setCreatedAt(java.lang.String value) {
      validate(fields()[5], value);
      this.createdAt = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder clearCreatedAt() {
      createdAt = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedAt' field.
      * @return The value.
      */
    public java.lang.String getUpdatedAt() {
      return updatedAt;
    }


    /**
      * Sets the value of the 'updatedAt' field.
      * @param value The value of 'updatedAt'.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder setUpdatedAt(java.lang.String value) {
      validate(fields()[6], value);
      this.updatedAt = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedAt' field has been set.
      * @return True if the 'updatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'updatedAt' field.
      * @return This builder.
      */
    public curthproductservice.avro.InventoryStatus.Builder clearUpdatedAt() {
      updatedAt = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InventoryStatus build() {
      try {
        InventoryStatus record = new InventoryStatus();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.inventoryType = fieldSetFlags()[1] ? this.inventoryType : (java.lang.String) defaultValue(fields()[1]);
        record.quantity = fieldSetFlags()[2] ? this.quantity : (java.lang.Integer) defaultValue(fields()[2]);
        record.productName = fieldSetFlags()[3] ? this.productName : (java.lang.String) defaultValue(fields()[3]);
        record.productType = fieldSetFlags()[4] ? this.productType : (java.lang.String) defaultValue(fields()[4]);
        record.createdAt = fieldSetFlags()[5] ? this.createdAt : (java.lang.String) defaultValue(fields()[5]);
        record.updatedAt = fieldSetFlags()[6] ? this.updatedAt : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InventoryStatus>
    WRITER$ = (org.apache.avro.io.DatumWriter<InventoryStatus>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InventoryStatus>
    READER$ = (org.apache.avro.io.DatumReader<InventoryStatus>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.inventoryType);

    out.writeInt(this.quantity);

    out.writeString(this.productName);

    out.writeString(this.productType);

    out.writeString(this.createdAt);

    out.writeString(this.updatedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.inventoryType = in.readString();

      this.quantity = in.readInt();

      this.productName = in.readString();

      this.productType = in.readString();

      this.createdAt = in.readString();

      this.updatedAt = in.readString();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.inventoryType = in.readString();
          break;

        case 2:
          this.quantity = in.readInt();
          break;

        case 3:
          this.productName = in.readString();
          break;

        case 4:
          this.productType = in.readString();
          break;

        case 5:
          this.createdAt = in.readString();
          break;

        case 6:
          this.updatedAt = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










