/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package curthproductservice.avro;
@org.apache.avro.specific.AvroGenerated
public enum ProductType implements org.apache.avro.generic.GenericEnumSymbol<ProductType> {
  ELECTRONICS, CLOTHING, FOOD, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductType\",\"namespace\":\"curthproductservice.avro\",\"symbols\":[\"ELECTRONICS\",\"CLOTHING\",\"FOOD\",\"OTHER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
